homeassistant:
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 41.817806
  longitude: -88.173401
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

#Enables Camera stream
ffmpeg:

logger:
  default: critical
  logs:
    homeassistant.components.http.ban: warning

# Text to speech
tts:
  - platform: google_translate
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switch.yaml
sensor: !include sensors.yaml
light: !include lights.yaml
camera: !include cameras.yaml

#Database Info
recorder:
  db_url: !secret db_url
  purge_keep_days: 180
  exclude:
    entities:
      - sun.sun #exclude sun data
    domains:
      - darksky

conversation:


  
#Zigbee Gateway
zha:
  usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db

weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key
    mode: daily

shopping_list:

mqtt:
  broker: "mosquitto"
  port: 1883
  username: !secret mosquitto_user 
  password: !secret mosquitto_password
  discovery: true
  discovery_prefix: homeassistant

python_script:
history_graph:
  gr1:
    name: Bedroom Status
    entities:
      - sensor.bedroom_temp
      - sensor.bedroom_humidity
      - sensor.bedroom_battery
    hours_to_show: 240
    refresh: 60

frontend:
  themes:
    slate:
      # Main colors
      primary-color: '#2980b9'
      accent-color: '#b58e31'
      dark-primary-color: '#2980b9'
      light-primary-color: '#2980b9'
      # Text colors
      primary-text-color: '#FFFFFF'
      text-primary-color: 'var(--primary-text-color)'
      secondary-text-color: '#b58e31'
      disabled-text-color: '#777777'
      label-badge-border-color: 'green'
      # Sidebar
      sidebar-icon-color: '#777777'
      # Background colors
      primary-background-color: '#222222'
      secondary-background-color: '#222222'
      divider-color: 'rgba(0, 0, 0, .12)'
      table-row-background-color: '#292929'
      table-row-alternative-background-color: '#292929'
      # Nav Menu
      paper-listbox-color: '#777777'
      paper-listbox-background-color: '#141414'
      paper-grey-50: 'var(--primary-text-color)'
      paper-grey-200: '#222222'
      # Paper card
      paper-card-header-color: '#2980b9'
      paper-card-background-color: '#292929'
      paper-dialog-background-color: '#292929'
      paper-item-icon-color: 'var(--primary-text-color)'
      paper-item-icon-active-color: '#b58e31'
      paper-item-icon_-_color: 'green'
      paper-item-selected_-_background-color: '#292929'
      paper-tabs-selection-bar-color: 'green'
      # Labels
      label-badge-red: 'var(--primary-color)'
      label-badge-text-color: 'var(--primary-text-color)'
      label-badge-background-color: '#222222'
      # Switches
      paper-toggle-button-checked-button-color: '#2980b9'
      paper-toggle-button-checked-bar-color: '#2980b9'
      paper-toggle-button-checked-ink-color: '#2980b9'
      paper-toggle-button-unchecked-button-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-ink-color: 'var(--disabled-text-color)'
      # Sliders
      paper-slider-knob-color: '#2980b9'
      paper-slider-knob-start-color: '#2980b9'
      paper-slider-pin-color: '#2980b9'
      paper-slider-active-color: '#2980b9'
      paper-slider-container-color: 'linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat'
      paper-slider-secondary-color: 'var(--secondary-background-color)'
      paper-slider-disabled-active-color: 'var(--disabled-text-color)'
      paper-slider-disabled-secondary-color: 'var(--disabled-text-color)'
      # Google colors
      google-red-500: '#b58e31'
      google-green-500: '#2980b9'
      #Changes to fix history/logbook menus
      lumo-primary-text-color: '#2980b9'
      lumo-secondary-text-color: '#2980b9'
      lumo-primary-color: '#2980b9'
      #Calendar day numbers
      lumo-body-text-color: '#b58e31'
      #Calendar/Date-Picker Background
      lumo-base-color: '#222222'
      #Month/Year header
      lumo-header-text-color: 'var(--lumo-body-text-color)'
      #DayOfWeek Header
      lumo-tertiary-text-color: 'var(--lumo-body-text-color)'
      lumo-shade: '#222222'
      lumo-shade-90pct: 'rgba(34, 34, 34, .9)'
      lumo-shade-80pct: 'rgba(34, 34, 34, .8)'
      lumo-shade-70pct: 'rgba(34, 34, 34, .7)'
      lumo-shade-60pct: 'rgba(34, 34, 34, .6)'
      lumo-shade-50pct: 'rgba(34, 34, 34, .5)'
      lumo-shade-40pct: 'rgba(34, 34, 34, .4)'
      lumo-shade-30pct: 'rgba(34, 34, 34, .3)'
      lumo-shade-20pct: 'rgba(34, 34, 34, .2)'
      lumo-shade-10pct: 'rgba(34, 34, 34, .1)'
      lumo-shade-5pct: 'rgba(34, 34, 34, .05)'
      lumo-tint-5pct: '#222222'
    